"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os,sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7rcw$$517)teiyc$fbid$k8*rjvjp4$k*gkm63esfkhdik6%6b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# SECURE_SSL_REDIRECT=False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'storages',
]

SITE_ID = 1
LOGIN_REDIRECT_URL = '/user/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dci1j9mk3m62p5',
        'USER': 'vfichiqouohorm',
        'PASSWORD': '030cfde955343a776de73c1dd6ff8697a078589234f6c148de071e020086f83b',
        'HOST': 'ec2-54-198-252-9.compute-1.amazonaws.com',
        'PORT': '5432'
    }
}


if 'test' in sys.argv:
    DATABASES['default'] = {'ENGINE':'django.db.backends.sqlite3'}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'

#MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static/images')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

try:
    import django_heroku
    django_heroku.settings(locals())
    
    CORS_REPLACE_HTTPS_REFERER      = True
    HOST_SCHEME                     = "https://"
    SECURE_SSL_REDIRECT             = True
    SESSION_COOKIE_SECURE           = True
    CSRF_COOKIE_SECURE              = True
    SECURE_HSTS_SECONDS             = 20000000
    SECURE_HSTS_INCLUDE_SUBDOMAINS  = True
    SECURE_FRAME_DENY               = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_PRELOAD = True
    DEBUG = False
    
except Exception:
    a = 3

#Access bucket for s3

AWS_ACCESS_KEY_ID = 'AKIAQSOKX4ZJSKZQXSNB'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'hoommatefinder-bucket'

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


"""/***
*  REFERENCES
*  Title: crash-course-CRM
*  Author: Dennis Ivy
*  Date: 05/02/2021
*  Code version: v17
*  URL: https://github.com/divanov11/crash-course-CRM/blob/part-17-Image-Upload/crm1_v17_image_upload/crm1/settings.py
*  Software License: <license software is released under>
*
***/"""

"""/***
*  REFERENCES
*  Title: crash-course-CRM
*  Author: Dennis Ivy
*  Date: 05/02/2021
*  Code version: v22
*  URL: https://github.com/divanov11/crash-course-CRM/blob/Part-22-S3-File-storage/crm1/crm1/settings.py
*  Software License: <license software is released under>
*
***/"""