# Generated by Django 3.1.5 on 2021-04-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget_lower',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget_upper',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car',
            field=models.CharField(choices=[('Have a car', 'Have a car'), ('Do not have a car', 'Do not have a car')], default='N', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other/Prefer not to say', 'Other/Prefer not to say')], default='O', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personality',
            field=models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert')], default='I', max_length=100),
        ),
    ]
