# Generated by Django 3.1.5 on 2021-04-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210409_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agemax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='agemin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget_lowerfilter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget_upperfilter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='carfilter',
            field=models.CharField(choices=[('Have a car', 'Have a car'), ('Do not have a car', 'Do not have a car')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='genderfilter',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other/Prefer not to say', 'Other/Prefer not to say')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='grad_yearmax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='grad_yearmin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_levelmax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_levelmin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='personalityfilter',
            field=models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert')], default='', max_length=100),
        ),
    ]
