# Generated by Django 3.1.5 on 2021-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210409_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=100)),
                ('receiver', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('previousMessage', models.IntegerField(default=None)),
            ],
        ),
    ]
