# Generated by Django 3.1.5 on 2021-04-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='previousMessage',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
