# Generated by Django 3.1.5 on 2021-04-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210424_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='oldMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=100)),
                ('receiver', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('previousMessage', models.IntegerField(default=None, null=True)),
                ('messageCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='messageCount',
            field=models.IntegerField(default=0),
        ),
    ]
