# Generated by Django 3.1.5 on 2021-04-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210424_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='mapboxLocation',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='oldmessages',
            name='nextMessage',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oldmessages',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='oldmessages',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genderfilter',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100),
        ),
    ]
